



## The jvsim container needs to be build manually first
## https://github.com/nkumar43212/jvsim

input-oc:
  image: juniper/open-nti-input-oc
  command: /go/bin/telegraf -debug
  environment:
   - "INFLUXDB_ADDR=opennti"
   - "OUTPUT_INFLUXDB=true"
   - "OUTPUT_STDOUT=true"
  volumes:
   - ./telegraf.conf:/etc/telegraf/telegraf.conf
   - /etc/localtime:/etc/localtime
  links:
   - opennti

opennti:
  image: juniper/open-nti:influxdb1.0
  volumes:
   - ./dashboard.json:/src/dashboards/dashboard.json
   - /etc/localtime:/etc/localtime
  ports:
   - "3000:3000"
   - "8083:8083"
   - "8086:8086"
